In [13]:
import pandas as pd
import sqlite3

# Connect to the database
conn = sqlite3.connect('predictions.db')

# Query the predictions table
query = "SELECT * FROM predictions"
df = pd.read_sql(query, conn)

# Close the connection
conn.close()

# Display the saved predictions
df

,id,duration,stops,days_left,departure_time,arrival_time,airline_air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,...,source_city_Kolkata,source_city_Mumbai,destination_city_Chennai,destination_city_Delhi,destination_city_Hyderabad,destination_city_Kolkata,destination_city_Mumbai,class_encoded,predicted_price,timestamp
0,1,10.0,1,30,0,4,1,0,0,0,...,0,0,0,0,1,0,0,0,b'\xd7\xa3p=\xe2j\xee@',2024-12-07 05:33:08